services:
  - type: web
    name: bot-cotacao-seguros-ultramsg
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: 1
      - key: PIP_NO_CACHE_DIR
        value: 1
    healthCheckPath: /health

